### PR TITLE
Add rancher-selinux's rpm install guide for EL9

### PR DESCRIPTION
**Pull request by andypitcher**
This PR implements this issue:
- https://github.com/rancher/rancher-selinux/issues/28

## Description

- This PR appends rancher-selinux rpm install by adding rancher-selinux's rpm install guide for `EL9` (setup yum repo)
- Changes (latest, v2.8, v2.7): reference-guides/rancher-security/selinux-rpm/about-rancher-selinux.md

```
# cat << EOF > /etc/yum.repos.d/rancher.repo
[rancher]
name=Rancher
baseurl=https://rpm.rancher.io/rancher/production/centos/9/noarch
enabled=1
gpgcheck=1
gpgkey=https://rpm.rancher.io/public.key
EOF
```

### CODE REVIEW

**Comment by btat** [comment]
Hi @andypitcher @macedogm, the reference issue mentions `After EL9 packages are officially released...`. Has that already happened (i.e. if this PR is approved can it be merged right away)?

**Comment by macedogm** [comment]
> Hi @andypitcher @macedogm, the reference issue mentions `After EL9 packages are officially released...`. Has that already happened (i.e. if this PR is approved can it be merged right away)?

No that hasn't happened yet and it depends on https://github.com/rancher/rancher/issues/43146. I believe that the best approach here is for us to track this and do the merge when the package is released. WDYT?

**Comment by btat** [comment]
> @btat no, that hasn't happened yet and it depends on [rancher/rancher#43146](https://github.com/rancher/rancher/issues/43146). I believe that the best approach here is for us to track this and do the merge when the package is released. WDYT?

Sounds good to me.

**Comment by andypitcher** [comment]
@macedogm @btat we should be good to go, the production packages have been released for RHEL9, see [comment](https://github.com/rancher/rancher/issues/43146#issuecomment-1871913480).
I just have rebased, so ready to review/merge.

**Pull request merged**
