### PR TITLE
Add iam:TagRole to minimum EKS permissions

### PR DESCRIPTION
**Pull request by mjura**
Fixes #[issue_number]

## Reminders

- See the [README](../README.md) for more details on how to work with the Rancher docs.

- Verify if changes pertain to other versions of Rancher. If they do, finalize the edits on one version of the page, then apply the edits to the other versions.

- If the pull request is dependent on an upcoming release, remember to add a "MERGE ON RELEASE" label and set the proper milestone.

### CODE REVIEW

**Review by yiannistri — APPROVED** [review]
LGTM! Bonus points for ordering them alphabetically :pray:

**Comment by mjura** [comment]
> Thank you @mjura! Approving the content addition to `/docs` however before officially approving the PR this content would also need to be applied to the `2.10/2.9/2.8` versioned docs as well. Would you be able to apply the updated content to those versions? If not I can assist with porting them to the relevant versions. Please let me know if you have any questions, thank you!

Could you please tell me how or to which branches I should submit backport of this change.

**Comment by sunilarjun** [comment]
Hello @mjura, the following files would need the changes applied and noting the paths below:

versioned_docs/version-2.10/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/eks.md
versioned_docs/version-2.9/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/eks.md
versioned_docs/version-2.8/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/eks.md

Let me know if any clarification is needed, thank you.

**Comment by mjura** [comment]
> Hello @mjura, the following files would need the changes applied and noting the paths below:
> 
> versioned_docs/version-2.10/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/eks.md versioned_docs/version-2.9/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/eks.md versioned_docs/version-2.8/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/eks.md
> 
> Let me know if any clarification is needed, thank you.

Thank you, I have backported this change to v2.10, v2.9 and v2.8.

Please review and let's merge it.

**Review by yiannistri — APPROVED** [review]
LGTM

**Comment by mjura** [comment]
@sunilarjun I think we can merge it now

**Review by sunilarjun — APPROVED** [review]
Thank you for addressing the changes!

**Pull request merged**
