### PR TITLE
[2.10.0] - Update SAML Pages with SLO Feature

### LINKED ISSUE #1331: Add SLO Configuration for SAML Providers
Related to https://github.com/rancher/dashboard/issues/10941

Per [comment](https://github.com/rancher/dashboard/issues/10941#issuecomment-2154569175):

> the documentation for rancher manager will need updating in regards to how they should configure the Single Logout on each of the SAML providers. Ex: https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-okta-saml

The Jira (SURE-3572) also has outlines of the new UX user experience for context.

### PR DESCRIPTION
**Pull request by sunilarjun**
Added information regarding new feature SAML SLO configuration through Rancher UI in SAML pages. Rancher issue link for reference: https://github.com/rancher/dashboard/issues/10941

Fixes docs issue #1331

### CODE REVIEW

**Comment by martyav** [comment]
Since we have so many "Merge on release" PRs for 2.9.0 and 2.8.6, I'm going to remove the label and add a "DO NOT MERGE" so that there's no chance this gets accidentally merged on the next release day

**Comment by sunilarjun** [comment]
Hello @aalves08! I am not able to tag you as a reviewer but would you be able to look over the content addition and see if there is anything missing or thats needs to be adjusted for the configuration steps, thank you!

**Review by btat — CHANGES_REQUESTED** [review]
If this is applicable to all SAML providers, Microsoft AD FS and Shibboleth are missing.

Not a blocker, but since this block is repeated multiple times per version it may be worth putting it in a partial/shared-files (similar to https://github.com/rancher/rancher-docs/pull/1142) to keep things DRY.

**Comment by sunilarjun** [comment]
@btat Added the content to Microsoft AD FS/Shibboleth/translation pages, as well as added _configure-slo.md file to shared files to go the partial route, thanks for reviewing!

**Comment by btat** [comment]
@sunilarjun can you update the base branch to v2.10.0 so that we don't publish the changes to /docs right away when this gets merged.

**Comment by sunilarjun** [comment]
@btat Just updated base branch, thanks for catching!

**Review by btat — APPROVED** [review]

**Comment by aalves08** [comment]
@sunilarjun, sorry for the late reply, but I've been held up with other topics

The `_configure-slo` looks fine. I would just add that the UI part about the `Log Out behavior` will only appear if that particular SAML provider allows for `SAML SLO`. Some may not provide that option, but I've only tested it with Okta so take that with a grain of salt (meaning that the backend will send a flag `logoutAllSupported`, which is the trigger for the UI to show the `Log Out behavior` UI part).

If the `Log Out behavior` UI is not available for a SAML provider, it means that the backend hasn't deemed it supported.

Probably worth mentioning because it may reduce number of support issues being filed 🙏

**Comment by sunilarjun** [comment]
Hello @aalves08 thanks for the response! I added in a note in this [docs PR](https://github.com/rancher/rancher-docs/pull/1550) here that hopefully clarifies, let me know if any other edits are needed. Thank you!

**Comment by aalves08** [comment]
That's perfect @sunilarjun 🙏 Thank you 🙇

**Pull request merged**
