### PR TITLE
[2.9.1] Impersonation - Known Issue Section

### PR DESCRIPTION
**Pull request by sunilarjun**
Adding in known issue warning to Impersonation section for v2.9.1.

Tied to https://github.com/rancher/rancher/issues/46790

### CODE REVIEW

**Review by btat — APPROVED** [review]
Approving.

Small nit that shouldn't block PR: should 'Known Issues' be singular here? Comparing it to when we use the note admonition, we don't use the plural form.

**Comment by sunilarjun** [comment]
> Approving.
> 
> Small nit that shouldn't block PR: should 'Known Issues' be singular here? Comparing it to when we use the note admonition, we don't use the plural form.

Agreed on it being singular, just edited. Thanks for the catch Billy!

**Comment by martyav** [comment]
Why no update to 2.6 versioned docs? https://github.com/rancher/rancher/issues/41988#issuecomment-1790820817

**Comment by sunilarjun** [comment]
I just made updates to maintained versions but I can add this update to v2.6 as well.

**Pull request merged**
