### PR TITLE
#991 refresh and restructure cloud provider guide section PART ONE: Restructure

### PR DESCRIPTION
**Pull request by martyav**
Part one of #991: Restructure

## Reminders

- See the [README](../README.md) for more details on how to work with the Rancher docs.

- Verify if changes pertain to other versions of Rancher. If they do, finalize the edits on one version of the page, then apply the edits to the other versions.

- If the pull request is dependent on an upcoming release, make sure to target the release branch instead of `main`.

## Description

This moves files in the /set-up-cloud-providers directory, creates two new subfolders for Amazon and vSphere respectively, and  addresses some broken links caused by the path changes.

## Comments

We should still refresh the pages in this section with CLI instructions and fill in any knowledge gaps.

When you review, you should build the site locally and preview it to make sure the pages are in the right place and links are working. I checked on my local machine before submitting the PR and didn't find anything odd.

### CODE REVIEW

**Review by btat — CHANGES_REQUESTED** [review]
Functional changes look good, but with the proposed design

- The naming scheme for files on the same topic (just for different providers) should be updated to match so it's obvious that they're about the same topic.

- Files for topics on the same topic for different providers ends up on different levels, which looks a bit odd when looking at the sidebar. I'm not sure what we should do about the vSphere ones, but at least for the Amazon instance `configure-amazon` should be the category instead of a child page.


Also, what's the plan for part two?

**Comment by martyav** [comment]
For part 2, we should review the other pages in this section and see if we need to include more detailed instructions to match the current Amazon page. We might also need to revise the instructions for clarity and consistency. When we determine the changes needed, we should work with an SME to update the pages (which commands to add, how to validate that something succeeded).

from https://github.com/rancher/rancher-docs/pull/844#issuecomment-1817233154:

> I agree with the feedback you've given on this PR in regards to including manual commands as well as validation steps, and looking at the documentation on other cloud providers, I do not feel like they meet the same level of depth.

**Review by sunilarjun — COMMENTED** [review]
Smoke tested the pages/links and everything looks good! I do agree that the file naming scheme should be similar for grouped topics.

**Comment by martyav** [comment]
Recently pushed changes to move the pages out of the deeply nested directories and fix links

**Review by btat — CHANGES_REQUESTED** [review]
The [latest build](https://github.com/rancher/rancher-docs/actions/runs/7225219412/job/19688166053?pr=1025) still shows a handful of broken links related to the files from this PR.

**Review by btat — APPROVED** [review]

**Pull request merged**
