### PR TITLE
Add 2.7 to versioned docs

### PR DESCRIPTION
**Pull request by btat**
Related: #662, #663
Note: `versioned_docs/version-2.7` generated when 05f194a3f35ec7fe5db1ed0a7fa5902f132d7587 the most recent commit in /docs.

This PR adds a versioned_docs/ entry for 2.7 so that there are versioned URLs for 2.7 pages, which is used by things like the UI. 

With this setup, `/docs` and the latest version in `versioned_docs` are the same (`versioned_docs/version-2.7` in this case) but will be appear to users labeled as `Latest` and `v2.7` respectively. For example, if v2.8 is introduced, a `versioned_docs/version-2.8` folder will be created and that will be a replica of `/docs` .

### CODE REVIEW

**Comment by martyav** [comment]
The official Docusaurus docs suggest updating the config so that we don't have to maintain 2 folders. I haven't tested that out myself on our docset so I don't know if there would be any problems implementing that:

image

From https://docusaurus.io/docs/versioning#configuring-versioning-behavior

**Comment by btat** [comment]
The example quoted is the setup we currently have, except that we don't set `current.path`.

Using the `/faq/general-faq` page as an example:
- Our current setup gives us https://ranchermanager.docs.rancher.com/faq/general-faq
- Based on feedback, we need both https://ranchermanager.docs.rancher.com/faq/general-faq and https://ranchermanager.docs.rancher.com/v2.7/faq/general-faq
  - A versioned link for things like the UI which need a static link
  - The unversioned link for things like rancher.com or marketing where we want users to access the latest page 

`path` doesn't take an array so we can't set it to both `/` and `/v2.7` which is why another folder in `versioned_docs` is needed. [Rancher Desktop](https://github.com/rancher-sandbox/docs.rancherdesktop.io/) has been using this model for a while now.

**Comment by btat** [comment]
Build is currently failing with `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory` as shown in https://github.com/rancher/rancher-docs/actions/runs/5181336107/jobs/9336713418?pr=665.

After some local testing, using the combination #667 and #668 allowed me to build without running into memory issues. Those should be merged before this one.

**Comment by martyav** [comment]
A more radical approach: Putting all content for latest in /shared-files, and importing it to the respective pages in /docs and /version_2.7. Since that would take more work than simply copying the files over to a new folder, we should probably leave off on it until 2.8 hits. However, it would give us a single source of truth, so that pages can't get out of sync, and it would dramatically reduce the size of the pages stored

**Comment by btat** [comment]
Rebased and applied 9f65c72d..ae741d3b to version-2.7 docs.

**Review by martyav — APPROVED** [review]

**Pull request merged**
