### PR TITLE
#1213 Instructions on altering minimum password length

### LINKED ISSUE #1213: Instructions on altering minimum password length
## Related Issues

https://github.com/rancher/rancher-docs/issues/593

https://github.com/rancher/dashboard/issues/6633

## Summary

By default, the minimum password length for accounts is 12 chars. 

Rancher v2.6.9 introduced the ability to update the minimum length from Global Settings in the UI.

Rancher v2.7.2 introduced further restrictions: password length must be a positive integer (or a string coerced into a positive integer value) between 2 and 256 chars long. Leading zeroes in octal values are allowed. Decimal values are not allowed (1 is valid, 01 is valid, 1.0 is not). 

We should describe how to alter the minimum password length and the associated restrictions.

### PR DESCRIPTION
**Pull request by martyav**
Fixes #1213
Related to #593 

## Reminders

- See the [README](../README.md) for more details on how to work with the Rancher docs.

- Verify if changes pertain to other versions of Rancher. If they do, finalize the edits on one version of the page, then apply the edits to the other versions.

- If the pull request is dependent on an upcoming release, make sure to target the release branch instead of `main`.

## Description

This describes how to modify a field that was added to Global Settings in v2.6: https://github.com/rancher/dashboard/pull/6801

### CODE REVIEW

**Review by sunilarjun — COMMENTED** [review]
The instructions look good overall, but do we want to note in the v2.7 instructions that password validation was added to possible input as of v2.7.2? (Not totally sure it's needed, just wanted to suggest as the v2.6 phrasing states when password length customization was added.)

**Comment by martyav** [comment]
@sunilarjun I'm kind of divided on it too...I think, ultimately, telling the user the requirements regardless of if the system actually validates the input provides guard rails for v2.6.9--2.7.1. If they enter bad input in those versions, the system won't reject it, but it's probably going to cause odd behavior.

**Comment by sunilarjun** [comment]
> @sunilarjun I'm kind of divided on it too...I think, ultimately, telling the user the requirements regardless of if the system actually validates the input provides guard rails for v2.6.9--2.7.1. If they enter bad input in those versions, the system won't reject it, but it's probably going to cause odd behavior. So, telling the user what the input should be is more useful than telling them when a validation was introduced.

That makes sense and thanks for elaborating Marty. I'll go ahead and approve as I agree with the thought process.

**Review by sunilarjun — APPROVED** [review]

**Comment by martyav** [comment]
I'm going to merge since I need this PR for the other password-related open PR (#1208)

**Pull request merged**
