### PR TITLE
#358 Glossary project

### LINKED ISSUE #358: Add a glossary of Rancher-specific terms
**Summary:**
Rancher (and other SUSE projects/products) use some jargon that can be confusing for newbies. 

**Details:**

Kubernetes already has some overhead in the form of jargon ("charts", "pods", etc.)

Rancher and other SUSE projects and products also come with their own jargon. It can sometimes be difficult to tell if something is a general Kubernetes term or if it's specific to Rancher or RKE.

Examples: 
* Rancher using "project" for, roughly, "namespace" (I realize this is because projects predate namespaces)
* RKE 2 using "machine" for "node"

Let's compile a list of our jargon and put it in the docs as a glossary.

---

The glossary pages we added to the docset include a lot of HTML tags. This note was originally listed on the glossary page files, explaining why:

> This page uses HTML definition list tags. dl indicates the start and end of a definition list. dt indicates the defined term, and dd the definition. These will stay in place until we upgrade to Docusaurus 3 and are able to add the remark-definition-list plugin for native Markdown syntax. We are currently blocked as the plugin requires a handler that isn't currently exposed. See https://github.com/facebook/docusaurus/discussions/8743#discussioncomment-6085581 and https://github.com/facebook/docusaurus/pull/9674

More context on this from #1125:

> We (@martyav & @sunilarjun) looked into adding a plugin that would provide native Markdown syntax for definition lists. We landed on this [page ](https://docusaurus.community/knowledge/markdown/definition-lists/), which has instructions on adding remark-deflist ([repo](https://github.com/Symbitic/remark-plugins/blob/master/packages/remark-deflist/README.md)) to your Docusaurus instance, but the instructions didn't seem to work for our config. I tried remark-definition-list ([repo](https://github.com/wataru-chocola/remark-definition-list)), but that didn't work either. While looking for a solution, I ran across this https://github.com/facebook/docusaurus/discussions/8743#discussioncomment-7778521on an https://github.com/facebook/docusaurus/discussions/8743complaining that the instructions for adding Remark plugins needed improvement. It seems that the plugins need a remark-rehype handler to be configured. There was a https://github.com/facebook/docusaurus/pull/9674to add this functionality to the Docusaurus config file, but I don't think it's available yet on Docusaurus 2. We might need to upgrade to Docusaurus 3. In the meantime, the HTML tags are perfectly functional.

### PR DESCRIPTION
**Pull request by martyav**
Fixes #358

## Reminders

- See the [README](../README.md) for more details on how to work with the Rancher docs.

- Verify if changes pertain to other versions of Rancher. If they do, finalize the edits on one version of the page, then apply the edits to the other versions.

- If the pull request is dependent on an upcoming release, make sure to target the release branch instead of `main`.

## Description

Adds a glossary of Rancher-related terms.

Since we were struggling to add a plugin that would provide prettier Markdown syntax for definition lists, we're using HTML tags. The tags are necessary for Algolia to index the terms and make them searchable.

I also included some CSS styling.

----

**List of terms to define**

- [x] ☰
- [x] ⋮
- [x] Apps
- [x] Apps & Marketplace
- [x] Catalogs (section)
- [x] Catalogs (Helm chart repos)
- [ ] Cloud credentials 
- [ ] Community (Rancher edition) -> discuss with Cam
- [ ] Deployment
- [x] Downstream cluster
- [x] Extensions
- [ ] External auth
- [x] Hosted cluster
- [x] Imported
- [ ] Integrations
- [ ] Hosted cluster
- [ ] Hosted pools
- [x] K3s
- [ ] Local auth
- [x] Local cluster
- [ ] Machine pool
- [x] Managed cluster
- [ ] Neuvector Prime
- [ ] Node template
- [ ] Prime
- [ ] Project
- [ ] Project resource quotas
- [ ] PSA
- [ ] PSA Config Template
- [ ] PSP
- [ ] Rancher chart
- [ ] Rancher CLI
- [x] Rancher Enterprise
- [ ] Rancher Kubernetes API (RK-API)
- [x] Rancher Kubernetes Engine
- [x] Rancher Prime
- [x] Rancher server
- [ ] Registered cluster
- [x] RKE1
- [x] RKE2
- [x] RKE Government
- [ ] Roles
- [ ] UI
- [x] Upstream cluster
- [ ] Users
- [x] Workload

----

Screenshot as of Feb 15 (latest):

image

## Comments

We (@martyav & @sunilarjun) looked into adding a plugin that would provide native Markdown syntax for definition lists. We landed on this [page ](https://docusaurus.community/knowledge/markdown/definition-lists/), which has instructions on adding `remark-deflist` ([repo](https://github.com/Symbitic/remark-plugins/blob/master/packages/remark-deflist/README.md)) to your Docusaurus instance, but the instructions didn't seem to work for our config. I tried `remark-definition-list` ([repo](https://github.com/wataru-chocola/remark-definition-list)), but that didn't work either. While looking for a solution, I ran across this [comment ](https://github.com/facebook/docusaurus/discussions/8743#discussioncomment-7778521) on an [issue ](https://github.com/facebook/docusaurus/discussions/8743) complaining that the instructions for adding Remark plugins needed improvement. It seems that the plugins need a `remark-rehype` handler to be configured. There was a [PR ](https://github.com/facebook/docusaurus/pull/9674) to add this functionality to the Docusaurus config file, but I don't think it's available yet on Docusaurus 2. We might need to upgrade to Docusaurus 3. In the meantime, the HTML tags are perfectly functional.

### CODE REVIEW

**Comment by martyav** [comment]
For the purposes of dividing up the word on definitions --

@LucasSaintarbor, could you do Managed Clusters through Rancher Enterprise, and @sunilarjun could you take RK-API through Upstream clusters?

Roughly, 
Me - A to M
Lucas - M to Rancher E
Sunil - Rancher F to Z

**Comment by sunilarjun** [comment]
Some definitions are still in progress but wanted to post the list here as it is nearing completion:

**Rancher Kubernetes API (RK-API)**
Versions: Rancher v2.8 and later

Users can utilize standard API requests with respect to available Rancher resources through the RK-API.

**Rancher Kubernetes Engine (RKE)**
A CNCF-certified Kubernetes distribution that runs entirely within Docker containers. There are two main versions of RKE available. The 1.x software line is referred to as RKE1. RKE2 or RKE Government is a Kubernetes distribution that focuses on security and compliance for U.S. Federal Government entities.

Related Terms: RKE1, the 1.x software line of RKE. 

**Rancher Prime**
Versions: Rancher v2.8 and later

Rancher Prime is a new edition of the commercial, enterprise offering built on the the same source code. Installation assets are hosted on a trusted registry owned and managed by Rancher with additional value coming in from security assurances, extended lifecycles, access to focused architectures and Kubernetes advisories.

Related terms: Rancher Enterprise

**Rancher Server**
Versions: All versions

Rancher Server is a Kubernetes management tool to deploy and run clusters anywhere and on any provider. Rancher includes all the software and downstream cluster components used to manage the entire Rancher deployment. 

Related terms: Rancher

**Registered Cluster**

**RKE1**
RKE1 is a certified Kubernetes distribution and CLI/library which creates and manages a Kubernetes cluster.

Related terms: RKE (Rancher Kubernetes Engine)

**RKE2**
RKE2 is a fully conformant Kubernetes distribution that focuses on security and compliance within the U.S. Federal Government sector.

Related Terms: RKE Government

**Roles**
Within Rancher, roles determine what actions a user can make within a cluster or project.

**UI**

**Upstream Cluster**
An upstream cluster is the local Kubernetes cluster that your Rancher installation is provisioned on.

**Users**

**Workload**
Workloads are objects that set deployment rules for pods. Based on these rules, Kubernetes performs the deployment and updates the workload with the current state of the application. Workloads let you define the rules for application scheduling, scaling, and upgrade.

**Comment by martyav** [comment]
Since https://github.com/rancher/rancher-docs/pull/1305 is merged, https://github.com/rancher/rancher-docs/pull/1332 is now open, and we've ported some of the comments from this PR to the parent issue, I'm closing this PR. Closing the PR helps clean up the repo as we have a number of very long-lived PRs currently open.

**Comment by martyav** [comment]
Since https://github.com/rancher/rancher-docs/pull/1305 is merged, https://github.com/rancher/rancher-docs/pull/1332 is now open, and we've ported some of the comments from this PR to the parent issue, I'm closing this PR. Closing the PR helps clean up the repo as we have a number of very long-lived PRs currently open.

**Pull request closed without merging**
